### ISSUE TITLE
Problem installing on symfony 4.4

### ISSUE THREAD

**Issue by developingjan** [artgris/MaintenanceBundle#7]
Hi everyone! I have a problem when I try to install on Symfony 4.4.
The console log:

Restricting packages listed in "symfony/symfony" to "4.4.*"
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - artgris/maintenance-bundle 1.0.8 requires symfony/framework-bundle ^2.3 || ^3.0 -> no matching package found.
    - artgris/maintenance-bundle 1.0.7 requires symfony/framework-bundle ^2.3 || ^3.0 -> no matching package found.
    - artgris/maintenance-bundle 1.0.6 requires symfony/framework-bundle ^2.3 || ^3.0 -> no matching package found.
    - artgris/maintenance-bundle 1.0.5 requires symfony/framework-bundle ^2.3 || ^3.0 -> no matching package found.
    - artgris/maintenance-bundle 1.0.4 requires symfony/framework-bundle ^2.3 || ^3.0 -> no matching package found.
    - artgris/maintenance-bundle 1.0.3 requires symfony/framework-bundle ^2.3 || ^3.0 -> no matching package found.
    - artgris/maintenance-bundle 1.0.2 requires symfony/framework-bundle ^2.3 || ^3.0 -> no matching package found.
    - artgris/maintenance-bundle 1.0.1 requires symfony/framework-bundle ^2.3 || ^3.0 -> no matching package found.
    - artgris/maintenance-bundle 1.0.0 requires symfony/framework-bundle ^2.3 || ^3.0 -> no matching package found.
    - Conclusion: remove doctrine/doctrine-bundle 2.2.2
    - Conclusion: don't install doctrine/doctrine-bundle 2.2.2
    - twig/twig v2.0.0 conflicts with doctrine/doctrine-bundle[2.2.2].
    - twig/twig v2.1.0 conflicts with doctrine/doctrine-bundle[2.2.2].
    - twig/twig v2.2.0 conflicts with doctrine/doctrine-bundle[2.2.2].
    - twig/twig v2.3.0 conflicts with doctrine/doctrine-bundle[2.2.2].
    - twig/twig v2.3.1 conflicts with doctrine/doctrine-bundle[2.2.2].
    - twig/twig v2.3.2 conflicts with doctrine/doctrine-bundle[2.2.2].
    - twig/twig v1.12.0 conflicts with doctrine/doctrine-bundle[2.2.2].
    - twig/twig v1.12.1 conflicts with doctrine/doctrine-bundle[2.2.2].
    - twig/twig v1.12.2 conflicts with doctrine/doctrine-bundle[2.2.2].
    - twig/twig v1.12.3 conflicts with doctrine/doctrine-bundle[2.2.2].
    - twig/twig v1.13.0 conflicts with doctrine/doctrine-bundle[2.2.2].
    - twig/twig v1.13.1 conflicts with doctrine/doctrine-bundle[2.2.2].
    - twig/twig v1.13.2 conflicts with doctrine/doctrine-bundle[2.2.2].
    - twig/twig v1.14.0 conflicts with doctrine/doctrine-bundle[2.2.2].
    - twig/twig v1.14.1 conflicts with doctrine/doctrine-bundle[2.2.2].
    - twig/twig v1.14.2 conflicts with doctrine/doctrine-bundle[2.2.2].
    - twig/twig v1.15.0 conflicts with doctrine/doctrine-bundle[2.2.2].
    - twig/twig v1.15.1 conflicts with doctrine/doctrine-bundle[2.2.2].
    - twig/twig v1.16.0 conflicts with doctrine/doctrine-bundle[2.2.2].
    - twig/twig v1.16.1 conflicts with doctrine/doctrine-bundle[2.2.2].
    - twig/twig v1.16.2 conflicts with doctrine/doctrine-bundle[2.2.2].
    - twig/twig v1.16.3 conflicts with doctrine/doctrine-bundle[2.2.2].
    - twig/twig v1.17.0 conflicts with doctrine/doctrine-bundle[2.2.2].
    - twig/twig v1.18.0 conflicts with doctrine/doctrine-bundle[2.2.2].
    - twig/twig v1.18.1 conflicts with doctrine/doctrine-bundle[2.2.2].
    - twig/twig v1.18.2 conflicts with doctrine/doctrine-bundle[2.2.2].
    - twig/twig v1.19.0 conflicts with doctrine/doctrine-bundle[2.2.2].
    - twig/twig v1.20.0 conflicts with doctrine/doctrine-bundle[2.2.2].
    - twig/twig v1.21.0 conflicts with doctrine/doctrine-bundle[2.2.2].
    - twig/twig v1.21.1 conflicts with doctrine/doctrine-bundle[2.2.2].
    - twig/twig v1.21.2 conflicts with doctrine/doctrine-bundle[2.2.2].
    - twig/twig v1.22.0 conflicts with doctrine/doctrine-bundle[2.2.2].
    - twig/twig v1.22.1 conflicts with doctrine/doctrine-bundle[2.2.2].
    - twig/twig v1.22.2 conflicts with doctrine/doctrine-bundle[2.2.2].
    - twig/twig v1.22.3 conflicts with doctrine/doctrine-bundle[2.2.2].
    - twig/twig v1.23.0 conflicts with doctrine/doctrine-bundle[2.2.2].
    - twig/twig v1.23.1 conflicts with doctrine/doctrine-bundle[2.2.2].
    - twig/twig v1.23.2 conflicts with doctrine/doctrine-bundle[2.2.2].
    - twig/twig v1.23.3 conflicts with doctrine/doctrine-bundle[2.2.2].
    - twig/twig v1.24.0 conflicts with doctrine/doctrine-bundle[2.2.2].
    - twig/twig v1.24.1 conflicts with doctrine/doctrine-bundle[2.2.2].
    - twig/twig v1.24.2 conflicts with doctrine/doctrine-bundle[2.2.2].
    - twig/twig v1.25.0 conflicts with doctrine/doctrine-bundle[2.2.2].
    - twig/twig v1.26.0 conflicts with doctrine/doctrine-bundle[2.2.2].
    - twig/twig v1.26.1 conflicts with doctrine/doctrine-bundle[2.2.2].
    - twig/twig v1.27.0 conflicts with doctrine/doctrine-bundle[2.2.2].
    - twig/twig v1.28.0 conflicts with doctrine/doctrine-bundle[2.2.2].
    - twig/twig v1.28.1 conflicts with doctrine/doctrine-bundle[2.2.2].
    - twig/twig v1.28.2 conflicts with doctrine/doctrine-bundle[2.2.2].
    - twig/twig v1.29.0 conflicts with doctrine/doctrine-bundle[2.2.2].
    - twig/twig v1.30.0 conflicts with doctrine/doctrine-bundle[2.2.2].
    - twig/twig v1.31.0 conflicts with doctrine/doctrine-bundle[2.2.2].
    - twig/twig v1.32.0 conflicts with doctrine/doctrine-bundle[2.2.2].
    - twig/twig v1.33.0 conflicts with doctrine/doctrine-bundle[2.2.2].
    - twig/twig v1.33.1 conflicts with doctrine/doctrine-bundle[2.2.2].
    - twig/twig v1.33.2 conflicts with doctrine/doctrine-bundle[2.2.2].
    - twig/twig v1.11.0 conflicts with doctrine/doctrine-bundle[2.2.2].
    - twig/twig v1.11.1 conflicts with doctrine/doctrine-bundle[2.2.2].
    - Installation request for doctrine/doctrine-bundle (locked at 2.2.2, required as ^2.2) -> satisfiable by doctrine/doctrine-bundle[2.2.2].
    - Conclusion: don't install pagerfanta/pagerfanta v2.5.1|install twig/twig v1.11.0|install twig/twig v1.11.1|install twig/twig v1.12.0|install twig/twig v1.12.1|install twig/twig v1.12.2|install twig/twig v1.12.3|install twig/twig v1.13.0|install twig/twig v1.13.1|install twig/twig v1.13.2|install twig/twig v1.14.0|install twig/twig v1.14.1|install twig/twig v1.14.2|install twig/twig v1.15.0|install twig/twig v1.15.1|install twig/twig v1.16.0|install twig/twig v1.16.1|install twig/twig v1.16.2|install twig/twig v1.16.3|install twig/twig v1.17.0|install twig/twig v1.18.0|install twig/twig v1.18.1|install twig/twig v1.18.2|install twig/twig v1.19.0|install twig/twig v1.20.0|install twig/twig v1.21.0|install twig/twig v1.21.1|install twig/twig v1.21.2|install twig/twig v1.22.0|install twig/twig v1.22.1|install twig/twig v1.22.2|install twig/twig v1.22.3|install twig/twig v1.23.0|install twig/twig v1.23.1|install twig/twig v1.23.2|install twig/twig v1.23.3|install twig/twig v1.24.0|install twig/twig v1.24.1|install twig/twig v1.24.2|install twig/twig v1.25.0|install twig/twig v1.26.0|install twig/twig v1.26.1|install twig/twig v1.27.0|install twig/twig v1.28.0|install twig/twig v1.28.1|install twig/twig v1.28.2|install twig/twig v1.29.0|install twig/twig v1.30.0|install twig/twig v1.31.0|install twig/twig v1.32.0|install twig/twig v1.33.0|install twig/twig v1.33.1|install twig/twig v1.33.2|install twig/twig v2.0.0|install twig/twig v2.1.0|install twig/twig v2.2.0|install twig/twig v2.3.0|install twig/twig v2.3.1|install twig/twig v2.3.2
    - Conclusion: remove pagerfanta/pagerfanta v2.5.1|install twig/twig v1.11.0|install twig/twig v1.11.1|install twig/twig v1.12.0|install twig/twig v1.12.1|install twig/twig v1.12.2|install twig/twig v1.12.3|install twig/twig v1.13.0|install twig/twig v1.13.1|install twig/twig v1.13.2|install twig/twig v1.14.0|install twig/twig v1.14.1|install twig/twig v1.14.2|install twig/twig v1.15.0|install twig/twig v1.15.1|install twig/twig v1.16.0|install twig/twig v1.16.1|install twig/twig v1.16.2|install twig/twig v1.16.3|install twig/twig v1.17.0|install twig/twig v1.18.0|install twig/twig v1.18.1|install twig/twig v1.18.2|install twig/twig v1.19.0|install twig/twig v1.20.0|install twig/twig v1.21.0|install twig/twig v1.21.1|install twig/twig v1.21.2|install twig/twig v1.22.0|install twig/twig v1.22.1|install twig/twig v1.22.2|install twig/twig v1.22.3|install twig/twig v1.23.0|install twig/twig v1.23.1|install twig/twig v1.23.2|install twig/twig v1.23.3|install twig/twig v1.24.0|install twig/twig v1.24.1|install twig/twig v1.24.2|install twig/twig v1.25.0|install twig/twig v1.26.0|install twig/twig v1.26.1|install twig/twig v1.27.0|install twig/twig v1.28.0|install twig/twig v1.28.1|install twig/twig v1.28.2|install twig/twig v1.29.0|install twig/twig v1.30.0|install twig/twig v1.31.0|install twig/twig v1.32.0|install twig/twig v1.33.0|install twig/twig v1.33.1|install twig/twig v1.33.2|install twig/twig v2.0.0|install twig/twig v2.1.0|install twig/twig v2.2.0|install twig/twig v2.3.0|install twig/twig v2.3.1|install twig/twig v2.3.2
    - twig/twig v2.4.0 conflicts with pagerfanta/pagerfanta[v2.5.1].
    - twig/twig v2.4.1 conflicts with pagerfanta/pagerfanta[v2.5.1].
    - twig/twig v2.4.2 conflicts with pagerfanta/pagerfanta[v2.5.1].
    - twig/twig v2.4.3 conflicts with pagerfanta/pagerfanta[v2.5.1].
    - twig/twig v2.4.4 conflicts with pagerfanta/pagerfanta[v2.5.1].
    - twig/twig v2.4.5 conflicts with pagerfanta/pagerfanta[v2.5.1].
    - twig/twig v2.4.6 conflicts with pagerfanta/pagerfanta[v2.5.1].
    - twig/twig v2.4.7 conflicts with pagerfanta/pagerfanta[v2.5.1].
    - twig/twig v2.4.8 conflicts with pagerfanta/pagerfanta[v2.5.1].
    - twig/twig v1.34.0 conflicts with pagerfanta/pagerfanta[v2.5.1].
    - twig/twig v1.34.1 conflicts with pagerfanta/pagerfanta[v2.5.1].
    - twig/twig v1.34.2 conflicts with pagerfanta/pagerfanta[v2.5.1].
    - twig/twig v1.34.3 conflicts with pagerfanta/pagerfanta[v2.5.1].
    - twig/twig v1.34.4 conflicts with pagerfanta/pagerfanta[v2.5.1].
    - Installation request for pagerfanta/pagerfanta (locked at v2.5.1) -> satisfiable by pagerfanta/pagerfanta[v2.5.1].
    - Installation request for artgris/maintenance-bundle ^1.0 -> satisfiable by artgris/maintenance-bundle[1.0.0, 1.0.1, 1.0.2, 1.0.3, 1.0.4, 1.0.5, 1.0.6, 1.0.7, 1.0.8, 1.0.9].
    - Conclusion: don't install twig/twig v3.1.1|install twig/twig v1.11.0|install twig/twig v1.11.1|install twig/twig v1.12.0|install twig/twig v1.12.1|install twig/twig v1.12.2|install twig/twig v1.12.3|install twig/twig v1.13.0|install twig/twig v1.13.1|install twig/twig v1.13.2|install twig/twig v1.14.0|install twig/twig v1.14.1|install twig/twig v1.14.2|install twig/twig v1.15.0|install twig/twig v1.15.1|install twig/twig v1.16.0|install twig/twig v1.16.1|install twig/twig v1.16.2|install twig/twig v1.16.3|install twig/twig v1.17.0|install twig/twig v1.18.0|install twig/twig v1.18.1|install twig/twig v1.18.2|install twig/twig v1.19.0|install twig/twig v1.20.0|install twig/twig v1.21.0|install twig/twig v1.21.1|install twig/twig v1.21.2|install twig/twig v1.22.0|install twig/twig v1.22.1|install twig/twig v1.22.2|install twig/twig v1.22.3|install twig/twig v1.23.0|install twig/twig v1.23.1|install twig/twig v1.23.2|install twig/twig v1.23.3|install twig/twig v1.24.0|install twig/twig v1.24.1|install twig/twig v1.24.2|install twig/twig v1.25.0|install twig/twig v1.26.0|install twig/twig v1.26.1|install twig/twig v1.27.0|install twig/twig v1.28.0|install twig/twig v1.28.1|install twig/twig v1.28.2|install twig/twig v1.29.0|install twig/twig v1.30.0|install twig/twig v1.31.0|install twig/twig v1.32.0|install twig/twig v1.33.0|install twig/twig v1.33.1|install twig/twig v1.33.2|install twig/twig v1.34.0|install twig/twig v1.34.1|install twig/twig v1.34.2|install twig/twig v1.34.3|install twig/twig v1.34.4|install twig/twig v2.0.0|install twig/twig v2.1.0|install twig/twig v2.2.0|install twig/twig v2.3.0|install twig/twig v2.3.1|install twig/twig v2.3.2|install twig/twig v2.4.0|install twig/twig v2.4.1|install twig/twig v2.4.2|install twig/twig v2.4.3|install twig/twig v2.4.4|install twig/twig v2.4.5|install twig/twig v2.4.6|install twig/twig v2.4.7|install twig/twig v2.4.8
    - Conclusion: remove twig/twig v3.1.1|install twig/twig v1.11.0|install twig/twig v1.11.1|install twig/twig v1.12.0|install twig/twig v1.12.1|install twig/twig v1.12.2|install twig/twig v1.12.3|install twig/twig v1.13.0|install twig/twig v1.13.1|install twig/twig v1.13.2|install twig/twig v1.14.0|install twig/twig v1.14.1|install twig/twig v1.14.2|install twig/twig v1.15.0|install twig/twig v1.15.1|install twig/twig v1.16.0|install twig/twig v1.16.1|install twig/twig v1.16.2|install twig/twig v1.16.3|install twig/twig v1.17.0|install twig/twig v1.18.0|install twig/twig v1.18.1|install twig/twig v1.18.2|install twig/twig v1.19.0|install twig/twig v1.20.0|install twig/twig v1.21.0|install twig/twig v1.21.1|install twig/twig v1.21.2|install twig/twig v1.22.0|install twig/twig v1.22.1|install twig/twig v1.22.2|install twig/twig v1.22.3|install twig/twig v1.23.0|install twig/twig v1.23.1|install twig/twig v1.23.2|install twig/twig v1.23.3|install twig/twig v1.24.0|install twig/twig v1.24.1|install twig/twig v1.24.2|install twig/twig v1.25.0|install twig/twig v1.26.0|install twig/twig v1.26.1|install twig/twig v1.27.0|install twig/twig v1.28.0|install twig/twig v1.28.1|install twig/twig v1.28.2|install twig/twig v1.29.0|install twig/twig v1.30.0|install twig/twig v1.31.0|install twig/twig v1.32.0|install twig/twig v1.33.0|install twig/twig v1.33.1|install twig/twig v1.33.2|install twig/twig v1.34.0|install twig/twig v1.34.1|install twig/twig v1.34.2|install twig/twig v1.34.3|install twig/twig v1.34.4|install twig/twig v2.0.0|install twig/twig v2.1.0|install twig/twig v2.2.0|install twig/twig v2.3.0|install twig/twig v2.3.1|install twig/twig v2.3.2|install twig/twig v2.4.0|install twig/twig v2.4.1|install twig/twig v2.4.2|install twig/twig v2.4.3|install twig/twig v2.4.4|install twig/twig v2.4.5|install twig/twig v2.4.6|install twig/twig v2.4.7|install twig/twig v2.4.8
    - artgris/maintenance-bundle 1.0.9 requires twig/twig ~1.11|~2.0 -> satisfiable by twig/twig[v1.11.0, v1.11.1, v1.12.0, v1.12.1, v1.12.2, v1.12.3, v1.13.0, v1.13.1, v1.13.2, v1.14.0, v1.14.1, v1.14.2, v1.15.0, v1.15.1, v1.16.0, v1.16.1, v1.16.2, v1.16.3, v1.17.0, v1.18.0, v1.18.1, v1.18.2, v1.19.0, v1.20.0, v1.21.0, v1.21.1, v1.21.2, v1.22.0, v1.22.1, v1.22.2, v1.22.3, v1.23.0, v1.23.1, v1.23.2, v1.23.3, v1.24.0, v1.24.1, v1.24.2, v1.25.0, v1.26.0, v1.26.1, v1.27.0, v1.28.0, v1.28.1, v1.28.2, v1.29.0, v1.30.0, v1.31.0, v1.32.0, v1.33.0, v1.33.1, v1.33.2, v1.34.0, v1.34.1, v1.34.2, v1.34.3, v1.34.4, v1.35.0, v1.35.1, v1.35.2, v1.35.3, v1.35.4, v1.36.0, v1.37.0, v1.37.1, v1.38.0, v1.38.1, v1.38.2, v1.38.3, v1.38.4, v1.39.0, v1.39.1, v1.40.0, v1.40.1, v1.41.0, v1.42.0, v1.42.1, v1.42.2, v1.42.3, v1.42.4, v1.42.5, v1.43.0, v1.43.1, v1.44.0, v1.44.1, v1.44.2, v2.0.0, v2.1.0, v2.10.0, v2.11.0, v2.11.1, v2.11.2, v2.11.3, v2.12.0, v2.12.1, v2.12.2, v2.12.3, v2.12.4, v2.12.5, v2.13.0, v2.13.1, v2.14.0, v2.14.1, v2.14.2, v2.14.3, v2.2.0, v2.3.0, v2.3.1, v2.3.2, v2.4.0, v2.4.1, v2.4.2, v2.4.3, v2.4.4, v2.4.5, v2.4.6, v2.4.7, v2.4.8, v2.5.0, v2.6.0, v2.6.1, v2.6.2, v2.7.0, v2.7.1, v2.7.2, v2.7.3, v2.7.4, v2.8.0, v2.8.1, v2.9.0].
    - Can only install one of: twig/twig[v2.11.3, v3.1.1].
    - Can only install one of: twig/twig[v2.12.0, v3.1.1].
    - Can only install one of: twig/twig[v2.12.1, v3.1.1].
    - Can only install one of: twig/twig[v2.12.2, v3.1.1].
    - Can only install one of: twig/twig[v2.12.3, v3.1.1].
    - Can only install one of: twig/twig[v2.12.4, v3.1.1].
    - Can only install one of: twig/twig[v2.12.5, v3.1.1].
    - Can only install one of: twig/twig[v2.13.0, v3.1.1].
    - Can only install one of: twig/twig[v2.13.1, v3.1.1].
    - Can only install one of: twig/twig[v2.14.0, v3.1.1].
    - Can only install one of: twig/twig[v2.14.1, v3.1.1].
    - Can only install one of: twig/twig[v2.14.2, v3.1.1].
    - Can only install one of: twig/twig[v2.14.3, v3.1.1].
    - Can only install one of: twig/twig[v1.35.0, v3.1.1].
    - Can only install one of: twig/twig[v1.35.1, v3.1.1].
    - Can only install one of: twig/twig[v1.35.2, v3.1.1].
    - Can only install one of: twig/twig[v1.35.3, v3.1.1].
    - Can only install one of: twig/twig[v1.35.4, v3.1.1].
    - Can only install one of: twig/twig[v1.36.0, v3.1.1].
    - Can only install one of: twig/twig[v1.37.0, v3.1.1].
    - Can only install one of: twig/twig[v1.37.1, v3.1.1].
    - Can only install one of: twig/twig[v1.38.0, v3.1.1].
    - Can only install one of: twig/twig[v1.38.1, v3.1.1].
    - Can only install one of: twig/twig[v1.38.2, v3.1.1].
    - Can only install one of: twig/twig[v1.38.3, v3.1.1].
    - Can only install one of: twig/twig[v1.38.4, v3.1.1].
    - Can only install one of: twig/twig[v1.39.0, v3.1.1].
    - Can only install one of: twig/twig[v1.39.1, v3.1.1].
    - Can only install one of: twig/twig[v1.40.0, v3.1.1].
    - Can only install one of: twig/twig[v1.40.1, v3.1.1].
    - Can only install one of: twig/twig[v1.41.0, v3.1.1].
    - Can only install one of: twig/twig[v1.42.0, v3.1.1].
    - Can only install one of: twig/twig[v1.42.1, v3.1.1].
    - Can only install one of: twig/twig[v1.42.2, v3.1.1].
    - Can only install one of: twig/twig[v1.42.3, v3.1.1].
    - Can only install one of: twig/twig[v1.42.4, v3.1.1].
    - Can only install one of: twig/twig[v1.42.5, v3.1.1].
    - Can only install one of: twig/twig[v1.43.0, v3.1.1].
    - Can only install one of: twig/twig[v1.43.1, v3.1.1].
    - Can only install one of: twig/twig[v1.44.0, v3.1.1].
    - Can only install one of: twig/twig[v1.44.1, v3.1.1].
    - Can only install one of: twig/twig[v1.44.2, v3.1.1].
    - Can only install one of: twig/twig[v2.10.0, v3.1.1].
    - Can only install one of: twig/twig[v2.11.0, v3.1.1].
    - Can only install one of: twig/twig[v2.11.1, v3.1.1].
    - Can only install one of: twig/twig[v2.11.2, v3.1.1].
    - Can only install one of: twig/twig[v2.5.0, v3.1.1].
    - Can only install one of: twig/twig[v2.6.0, v3.1.1].
    - Can only install one of: twig/twig[v2.6.1, v3.1.1].
    - Can only install one of: twig/twig[v2.6.2, v3.1.1].
    - Can only install one of: twig/twig[v2.7.0, v3.1.1].
    - Can only install one of: twig/twig[v2.7.1, v3.1.1].
    - Can only install one of: twig/twig[v2.7.2, v3.1.1].
    - Can only install one of: twig/twig[v2.7.3, v3.1.1].
    - Can only install one of: twig/twig[v2.7.4, v3.1.1].
    - Can only install one of: twig/twig[v2.8.0, v3.1.1].
    - Can only install one of: twig/twig[v2.8.1, v3.1.1].
    - Can only install one of: twig/twig[v2.9.0, v3.1.1].
    - Installation request for twig/twig (locked at v3.1.1) -> satisfiable by twig/twig[v3.1.1].

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://getcomposer.org/doc/04-schema.md#minimum-stability> for more details.
 - It's a private package and you forgot to add a custom repository to find it

Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.

Installation failed, reverting ./composer.json to its original content.

**Comment by artgris** [comment]
Hi, 

It's fixed in release 1.1.1, thx.
