### ISSUE TITLE
Can't allow access by IP address.

### ISSUE THREAD

**Issue by ericc06** [artgris/MaintenanceBundle#8]
Hi,
I can't allow access to my website while in maintenance mode with my public IP address.

Here is my artgris_maintenance.yaml:

artgris_maintenance:
    enable: true
    ips: ["11.22.33.44"]
    response: 503 

where 11.22.33.44 is my public IP address as given by https://www.whatismyip.com/
When I access my website from my PC through the Internet, all I can see is the maintenance page.

Symfony 5.2.10
Artgris MaintenanceBundle 1.1

Thank you,
Eric

**Comment by artgris** [comment]
Hi @ericc06, 

try to clear the prod cache on your online server.

**Comment by ericc06** [comment]
Sorry, I forgot to say that I cleared the cache and that my website is in the _prod_ environment.

**Comment by artgris** [comment]
try to catch $_SERVER['REMOTE_ADDR'] on your server and compare with your ips conf.

Are you on an online server with APP_ENV=prod ?

**Comment by ericc06** [comment]
Yes, my website is online and configured with APP_ENV=prod.

But the $_SERVER['REMOTE_ADDR'] variable does **not** contain my public IP address, but a private one (172.16.2.1).
I have to understand why.
The website is hosted on Azure. I'm going to read their documentation...

On the other hand, if in the Twig template I display the app.request object, I can see my public IP address:
X-CLIENT-IP: 88.160.x.y
X-CLIENT-PORT: 24989
X-FORWARDED-FOR: 88.160.x.y:24989

**Comment by ericc06** [comment]
Due to Azure (like many other providers) architecture, with load balancers and other network equipments in front of the web server, we can't get the remote IP address with $_SERVER['REMOTE_ADDR'].

Do you have an idea to make the bundle work in this case?

**Comment by artgris** [comment]
Hi, yes i need to test HTTP_X_FORWARDED_FOR or used $request->getClientIp().

**Comment by ericc06** [comment]
I'm sorry, the issue is not fixed in my case.
