### ISSUE TITLE
Still can't allow access by IP address.

### ISSUE THREAD

**Issue by ericc06** [artgris/MaintenanceBundle#9]
Hi,
In spite of the recent enhancement (issue [#8](https://github.com/artgris/MaintenanceBundle/issues/8)), I still can't allow access to my website hosted on Azure while in maintenance mode with my public IP address.

The site is in production environment (APP_ENV=prod) and the cache is cleared.

Here is my artgris_maintenance.yaml:

artgris_maintenance:
enable: true
ips: ["11.22.33.44"]
response: 503

where 11.22.33.44 is my public IP address as given by https://www.whatismyip.com/
When I access my website from my PC through the Internet, all I can see is the maintenance page.

Symfony 5.2.10
Artgris MaintenanceBundle 1.1.2

Thank you,
Eric

**Comment by artgris** [comment]
Have you **Configured Symfony to Work behind a Load Balancer or a Reverse Proxy** ? :
: https://symfony.com/doc/current/deployment/proxies.html#solution-settrustedproxies

**Comment by ericc06** [comment]
No, I have not.
Let me take a look at it.
Thank you.
